"""
Django settings for voter_mang_sys project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w^w75v0)bmgunxwhmmagl0bp*1rf$p^u9q-ca$2!%+q%(8f7=&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = eval(os.getenv("ALLOWED_HOSTS"))

ALLOWED_HOSTS = ["172.20.1.101","59.95.99.182","127.0.0.1", "localhost", "172.20.1.155", ".ngrok-free.app", ".ngrok-free.dev"]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=18),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=0),     # effectively disable refresh
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Application definition
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

# # settings.py
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'application',
    'whatsapp_service',
    'rest_framework',
    "channels",
    "notifications",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'voter_mang_sys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'voter_mang_sys.wsgi.application'
ASGI_APPLICATION = "voter_mang_sys.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                "redis://:Amit%40123@172.20.1.155:6379/0"
            ],
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://:Amit%40123@172.20.1.155:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,  # VERY IMPORTANT
        }
    }
}
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "whatsapp_db",      # your DB name
        "USER": "postgres",        # your username
        "PASSWORD": "postgres",
        "HOST": "172.20.1.155",       # or 172.20.1.155
        "PORT": "5432",
    }
}


VERIFY_TOKEN = os.getenv("WP_VERIFY_TOKEN")
MESSAGE_URL = os.getenv("MESSAGE_URL")
UPLOAD_URL = os.getenv("UPLOAD_URL")
ACCESS_TOKEN = os.getenv("WP_ACCESS_TOKEN")


WP_ACCESS_TOKEN="EAATvXwkH2M4BQGVUbaqi5gpg2RNMRbj835YCCi9XCzOV3oFEfFTadxx78S9de2eoI1Co8YiZAZCx79MiamrdPl5qNnI0ZAkobZBrljLcWaVoltDDFBFsXZBZBIbUdZBPZAulNqpYneOm8HOv59KZApdIrLKxovZClbwpmtZAHj6BOoz7qQRm4w2ZBaN0wy79t7CuK7xZADZC3ErslLt5GjspwOj8Vb5czkP2EqZAroSiyVJJlH0cSStpoaDVZAbdAkYrbUclBMK8YDW4snDtZA9WNTZCnhsYxvf8znRHdb4sO7JCmB6wZDZD"
WP_VERIFY_TOKEN="Toyam_orchid_token"
MESSAGE_URL="https://graph.facebook.com/v24.0/946219375236764/messages"
UPLOAD_URL="https://graph.facebook.com/v24.0/946219375236764/media"
AWS_ACCESS_KEY_ID= os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY= os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_S3_BUCKET_NAME= os.getenv("AWS_S3_BUCKET_NAME")
AWS_S3_REGION_NAME= os.getenv("AWS_S3_REGION_NAME")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'