# Generated by Django 5.2.9 on 2025-12-05 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('whatsapp_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=200, unique=True)),
                ('sender', models.CharField(choices=[('admin', 'Admin'), ('sub-admin', 'Sub Admin'), ('volunteer', 'Volunteer'), ('voter', 'Voter')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('media_id', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('template', 'Template'), ('location', 'Location')], default='text', max_length=20)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, db_column='admin_pk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_messages', to='whatsapp_service.admin')),
                ('reply_to', models.ForeignKey(blank=True, db_column='reply_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='whatsapp_service.voterchatmessage')),
                ('subadmin', models.ForeignKey(blank=True, db_column='subadmin_pk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subadmin_messages', to='whatsapp_service.subadmin')),
                ('volunteer', models.ForeignKey(blank=True, db_column='volunteer_pk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_messages', to='whatsapp_service.volunteer')),
                ('voter', models.ForeignKey(blank=True, db_column='voter_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='application.voterlist')),
            ],
            options={
                'db_table': 'voter_chat_messages',
                'indexes': [models.Index(fields=['voter', 'sent_at'], name='voter_chat__voter_i_52abf3_idx'), models.Index(fields=['admin', 'sent_at'], name='voter_chat__admin_p_e9078f_idx'), models.Index(fields=['subadmin', 'sent_at'], name='voter_chat__subadmi_e3ff4b_idx'), models.Index(fields=['volunteer', 'sent_at'], name='voter_chat__volunte_a307f3_idx'), models.Index(fields=['sender', 'sent_at'], name='voter_chat__sender_fbdd68_idx')],
            },
        ),
    ]
