# Generated by Django 5.2.9 on 2025-12-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoterList',
            fields=[
                ('voter_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('sr_no', models.IntegerField()),
                ('voter_id', models.CharField(blank=True, max_length=20, null=True)),
                ('voter_name_marathi', models.TextField(blank=True, null=True)),
                ('voter_name_eng', models.TextField(blank=True, null=True)),
                ('initial_full_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('middle_name', models.TextField(blank=True, null=True)),
                ('kramank', models.CharField(blank=True, max_length=20, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('address_line1', models.TextField(blank=True, null=True)),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('address_line3', models.TextField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('age_eng', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('gender_eng', models.CharField(blank=True, max_length=10, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('alternate_mobile1', models.CharField(blank=True, max_length=10, null=True)),
                ('alternate_mobile2', models.CharField(blank=True, max_length=10, null=True)),
                ('ward_no', models.IntegerField()),
            ],
            options={
                'db_table': 'voter_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoterTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'voter_tags',
                'managed': False,
            },
        ),
    ]
