# Generated by Django 5.2.8 on 2025-12-07 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='role', max_length=100, unique=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'voter_role_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoterRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('husband', 'Husband'), ('wife', 'Wife'), ('child', 'Child'), ('brother', 'Brother'), ('sister', 'Sister'), ('sibling', 'Sibling')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='application.voterlist')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='application.voterlist')),
            ],
            options={
                'unique_together': {('voter', 'related_voter', 'relation')},
            },
        ),
    ]
