# Generated by Django 5.2.8 on 2025-12-07 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_roles_voterrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterRelationshipDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relation_with_voter', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('husband', 'Husband'), ('wife', 'Wife'), ('child', 'Child'), ('brother', 'Brother'), ('sister', 'Sister'), ('sibling', 'Sibling')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_voter', models.ForeignKey(db_column='related_voter_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_to', to='application.voterlist')),
                ('voter', models.ForeignKey(db_column='voter_list_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relations', to='application.voterlist')),
            ],
            options={
                'db_table': 'voter_relationship_details',
                'unique_together': {('voter', 'related_voter', 'relation_with_voter')},
            },
        ),
        migrations.DeleteModel(
            name='VoterRelation',
        ),
    ]
