# Generated by Django 5.2.8 on 2025-12-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_voterrelationshipdetails_delete_voterrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voterrelationshipdetails',
            options={'managed': False},
        ),
    ]
