# Generated by Django 5.2.8 on 2025-12-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_voterrelationshipdetails_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('caste_id', models.AutoField(primary_key=True, serialize=False)),
                ('caste_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'voter_caste_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('occupation_id', models.AutoField(primary_key=True, serialize=False)),
                ('occupation_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'voter_occupation_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('religion_id', models.AutoField(primary_key=True, serialize=False)),
                ('religion_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'voter_religion_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoterUserMaster',
            fields=[
                ('voter_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('f_name', models.CharField(blank=True, max_length=100, null=True)),
                ('m_name', models.CharField(blank=True, max_length=100, null=True)),
                ('l_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'voter_user_master',
                'managed': False,
            },
        ),
    ]
