# Generated by Django 5.2.9 on 2025-12-11 06:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_voterrelationshipdetails_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('caste_id', models.AutoField(primary_key=True, serialize=False)),
                ('caste_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'voter_caste_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('occupation_id', models.AutoField(primary_key=True, serialize=False)),
                ('occupation_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'voter_occupation_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('religion_id', models.AutoField(primary_key=True, serialize=False)),
                ('religion_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'voter_religion_master',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='voterlist',
            options={'managed': False, 'ordering': ['voter_list_id']},
        ),
        migrations.CreateModel(
            name='VoterUserMaster',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('mobile_no', models.CharField(validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number', regex='^[679]\\d{9}$')])),
                ('password', models.TextField(blank=True, null=True)),
                ('confirm_password', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='application.roles')),
            ],
            options={
                'db_table': 'voter_user_master',
            },
        ),
    ]
