# Generated by Django 5.2.8 on 2025-12-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_caste_occupation_religion_voterusermaster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voterlist',
            options={'managed': False, 'ordering': ['voter_list_id']},
        ),
        migrations.AlterModelOptions(
            name='voterusermaster',
            options={},
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.voterusermaster')),
            ],
            options={
                'db_table': 'activity_logs',
                'managed': True,
            },
        ),
    ]
