# Generated by Django 5.2.8 on 2025-12-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_voterlist_options_and_more'),
    ]

    operations = []
