# Generated by Django 5.2.8 on 2025-12-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_sync_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='voterusermaster',
            options={'managed': False},
        ),
    ]
