# Generated by Django 5.2.8 on 2025-12-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitylog',
            table='voter_activity_log',
        ),
    ]
