# Generated by Django 5.2.8 on 2025-12-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_activitylog_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voterlist',
            options={'managed': False},
        ),
    ]
