# Generated by Django 5.2.8 on 2025-12-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_voterlist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_module_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoterModuleMaster',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100, unique=True)),
                ('module_code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'voter_module_master',
                'ordering': ['module_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedLoginExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_base64', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
            ],
        ),
    ]
