# Generated by Django 5.2.8 on 2025-12-17 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_rolemodulepermission_votermodulemaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterPrintDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name_marathi', models.TextField(blank=True, null=True)),
                ('yadivibhag', models.CharField(blank=True, max_length=20, null=True)),
                ('anukramank', models.CharField(blank=True, max_length=20, null=True)),
                ('voterid', models.CharField(blank=True, max_length=20, null=True)),
                ('voting_center_name', models.TextField(blank=True, null=True)),
                ('voting_center_address', models.TextField(blank=True, null=True)),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_details', to='application.voterlist')),
            ],
            options={
                'db_table': 'voter_print_details',
            },
        ),
    ]
