# Generated by Django 5.2.8 on 2025-12-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_voterprintdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voterprintdetails',
            options={'managed': False},
        ),
    ]
