# Generated by Django 5.2.8 on 2025-12-18 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_voterprintdetails_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('voter_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_voters', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_matches', to='application.voterlist')),
            ],
            options={
                'unique_together': {('user', 'mobile_no')},
            },
        ),
    ]
