# Generated by Django 5.2.8 on 2025-12-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_uservotercontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterList2',
            fields=[
                ('sr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('voter_id', models.CharField(blank=True, max_length=200, null=True)),
                ('voter_name_marathi', models.CharField(blank=True, max_length=1000, null=True)),
                ('voter_name_english', models.CharField(blank=True, max_length=1000, null=True)),
                ('kramank', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('age_marathi', models.CharField(blank=True, max_length=50, null=True)),
                ('age_english', models.CharField(blank=True, max_length=50, null=True)),
                ('gender_marathi', models.CharField(blank=True, max_length=50, null=True)),
                ('gender_english', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'voter_list_2',
                'managed': False,
            },
        ),
    ]
