# Generated by Django 5.2.8 on 2025-12-23 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_voterlist2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('source', models.CharField(default='mobile', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voter_user_contact_payload',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='VoterList2',
        ),
        migrations.AlterUniqueTogether(
            name='uservotercontact',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='uservotercontact',
            index=models.Index(fields=['user', 'mobile_no'], name='application_user_id_e6a9c2_idx'),
        ),
        migrations.AlterModelTable(
            name='voterlist',
            table='final_voter_list',
        ),
        migrations.AddField(
            model_name='usercontactpayload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_payloads', to=settings.AUTH_USER_MODEL),
        ),
    ]
