# Generated by Django 6.0 on 2025-12-27 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('template_language', models.CharField(default='en_US', max_length=20)),
                ('body_param_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'template_names',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='template_na_name_6c0887_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoterChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=200, unique=True)),
                ('sender', models.CharField(choices=[('user', 'User'), ('voter', 'Voter')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('media_id', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('template', 'Template'), ('location', 'Location'), ('reaction', 'Reaction')], default='text', max_length=20)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sender_role', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_role_id', models.IntegerField(blank=True, null=True)),
                ('reply_to', models.ForeignKey(blank=True, db_column='reply_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='whatsapp_service.voterchatmessage')),
                ('sender_user', models.ForeignKey(blank=True, db_column='sender_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_messages', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(blank=True, db_column='voter_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='application.voterlist')),
            ],
            options={
                'db_table': 'voter_chat_messages',
                'indexes': [models.Index(fields=['voter', 'sent_at'], name='voter_chat__voter_i_52abf3_idx'), models.Index(fields=['sender_user', 'sent_at'], name='voter_chat__sender__7c8d5e_idx'), models.Index(fields=['sender', 'sent_at'], name='voter_chat__sender_fbdd68_idx')],
            },
        ),
    ]
