# Generated by Django 5.2.9 on 2025-12-05 09:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('full_name', models.CharField(blank=True, max_length=360, null=True)),
                ('mobile_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter 10 digit mobile number', regex='^\\d{10}$')])),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'admin',
                'indexes': [models.Index(fields=['mobile_no'], name='admin_mobile__6b87c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('full_name', models.CharField(blank=True, max_length=360, null=True)),
                ('mobile_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter 10 digit mobile number', regex='^\\d{10}$')])),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_pk', models.ForeignKey(db_column='admin_pk', on_delete=django.db.models.deletion.CASCADE, related_name='subadmins', to='whatsapp_service.admin')),
            ],
            options={
                'db_table': 'sub_admin',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('full_name', models.CharField(blank=True, max_length=360, null=True)),
                ('mobile_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter 10 digit mobile number', regex='^\\d{10}$')])),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subadmin_pk', models.ForeignKey(db_column='subadmin_pk', on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='whatsapp_service.subadmin')),
            ],
            options={
                'db_table': 'volunteer',
            },
        ),
        migrations.AddIndex(
            model_name='subadmin',
            index=models.Index(fields=['admin_pk'], name='sub_admin_admin_p_744cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='subadmin',
            index=models.Index(fields=['mobile_no'], name='sub_admin_mobile__622bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['subadmin_pk'], name='volunteer_subadmi_520516_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['mobile_no'], name='volunteer_mobile__de9ad0_idx'),
        ),
    ]
