# Generated by Django 5.2.9 on 2025-12-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatename',
            name='template_language',
            field=models.CharField(default='en_US', max_length=20),
        ),
    ]
