# Generated by Django 5.2.9 on 2025-12-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('whatsapp_service', '0002_voterchatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'template_names',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='template_na_name_6c0887_idx')],
            },
        ),
    ]
