# Generated by Django 5.2.9 on 2025-12-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_service', '0002_templatename_template_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatename',
            name='body_param_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
