# Generated by Django 5.2.8 on 2025-12-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_service', '0003_templatename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='subadmin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='password',
        ),
        migrations.AddField(
            model_name='admin',
            name='activation_key',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='subadmin',
            name='activation_key',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='activation_key',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
